name: SimpleLobby
version: '1.0.4'
main: cz.nerkub.simpleLobby.SimpleLobby
api-version: '1.20'

commands:
  setlobby:
    description: set a lobby
    usage: /<command>
  lobby:
    description: teleport to a lobby
    usage: /<command>
  slreload:
    description: reload config.yml
    usage: /<command>